### ISSUE TITLE
Signup Pages

### ISSUE THREAD

**Issue by shashank1503-cipher** [shashank1503-cipher/partnersincrime-frontend#3]
Create the signup pages like this.

![image](https://user-images.githubusercontent.com/54381338/145433558-8552d24c-ac2c-4272-bcd6-7902d766d42d.png)
![image](https://user-images.githubusercontent.com/54381338/145433630-ecf9f613-3aaa-444a-8b8e-50c916a52708.png)

Design Changes are Welcome

**Comment by ishaan5199** [comment]
can do this one :)

**Comment by shashank1503-cipher** [comment]
Good to go @ishaan5199
