### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by shashank1503-cipher** [shashank1503-cipher/partnersincrime-frontend#5]
Navbar
![image](https://user-images.githubusercontent.com/54381338/145435126-c8d0b349-d7e9-4f94-834f-4e79e1c9fe26.png)

Design Changes are welcome

**Comment by Techocrat** [comment]
Chill guyzz, I will handle this!

**Comment by shashank1503-cipher** [comment]
Good to go @Techocrat

**Comment by prashant6802** [comment]
add me in

**Comment by shashank1503-cipher** [comment]
@prashant6802 this issue is already assigned to @Techocrat  
There are other issues available

**Comment by junior-geek04** [comment]
I would like to collaborate in this

**Comment by shashank1503-cipher** [comment]
Good Work @Techocrat
